apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceapp: api-servicemonitor
  name: api-servicemonitor
  namespace: monitoring
spec:
  endpoints:
    - port: http
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: api
