name: 'exp: run-experiment'
on:
  push:
    branches:
      - exp
      - exp-python
jobs:
  run-experiment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: jupyterhub/action-k3s-helm@v2
        with:
          k3s-version: v1.21.11+k3s1
      - run: |
          kubectl version
          kubectl get pods --all-namespaces
      # - uses: docker/setup-buildx-action@v1
      #   with:
      #     install: true
      - run: |
          docker build -t api:dev .
          docker save --output api-dev.tar api:dev
      - run: |
          docker build -t k6:dev -f k6.Dockerfile .
          docker save --output k6-dev.tar k6:dev
      - run: |
          sudo k3s ctr images import api-dev.tar
          sudo k3s ctr images import k6-dev.tar
      - run: |
          kubectl apply -f deploy/api --recursive
          kubectl -n default wait deploy/api --for condition=available --timeout 5m
      - run: |
          kubectl delete service/metrics-server -n kube-system
          kubectl delete deployment.apps/metrics-server -n kube-system
          kubectl delete apiservices.apiregistration.k8s.io v1beta1.metrics.k8s.io
          kubectl delete clusterroles.rbac.authorization.k8s.io system:aggregated-metrics-reader
      - run: |
          git clone -b release-0.9 --single-branch https://github.com/prometheus-operator/kube-prometheus
          cd kube-prometheus
          kubectl create -f manifests/setup
          until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done
          kubectl create -f manifests/
      - run: kubectl -n default autoscale deploy/api --cpu-percent=65 --min=3 --max=20
      - run: sleep 1m
      - run: kubectl apply -f deploy/k6 --recursive
      - run: sleep 1m
      - if: always()
        run: kubectl -n default get pods
      - run: sleep 27m
      - if: always()
        run: kubectl top pods
      - if: always()
        run: kubectl -n default describe hpa/api
      - if: always()
        run: kubectl -n default describe deploy/api
      - if: always()
        run: kubectl -n default logs pod/k6
