name: 'exp: run-experiment'
on:
  push:
    branches:
      - exp
      - exp-python
jobs:
  run-experiment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: jupyterhub/action-k3s-helm@v2
        with:
          k3s-version: v1.21.11+k3s1
      - run: |
          kubectl version
          kubectl get pods --all-namespaces
      - run: |
          docker build -t api:dev .
          docker save --output api-dev.tar api:dev
      - run: |
          sudo k3s ctr images import api-dev.tar
